spring:

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:

        - id: product_route
          uri: lb://demomarket-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://demomarket-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://demomarket-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://demomarket-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: demomarket_host_route
          uri: lb://demomarket-product
          predicates:
            - Host=demomarket.com

        - id: demomarket_search_route
          uri: lb://demomarket-search
          predicates:
            - Host=search.demomarket.com

        - id: demomarket_auth_route
          uri: lb://demomarket-auth-server
          predicates:
            - Host=auth.demomarket.com


  application:
    name: demomarket-gateway